### ISSUE TITLE
Title bar doesn't match the Gnome desktop

### ISSUE THREAD

**Issue by Mars7x** [flathub/info.cemu.Cemu#56] opened 2023-07-08 19:30 UTC
The minimize and maximize buttons are on the title bar even with them turned off by default. It also seems to have the app icon on the left, which I'm pretty sure is a KDE thing. This doesn't happen on the AppImage build.

![Screenshot from 2023-07-08 15-27-30](https://github.com/flathub/info.cemu.Cemu/assets/112448675/6337b98a-aae4-49a8-9ae2-9b60daeedabc)

**Comment by ColinKinloch** [comment] 2023-08-03 21:10
Does this happen if you force x11?
Try either `flatpak run --nosocket=wayland info.cemu.Cemu` or use flatseal to block access to the wayland socket.

**Comment by ColinKinloch** [comment] 2023-08-03 21:14
I'm going to say that this is a duplicate of #17.

**Closed by ColinKinloch** 2023-08-03 21:14 UTC

**Comment by Mars7x** [comment] 2023-08-03 21:17
> Does this happen if you force x11?
> 
> Try either `flatpak run --nosocket=wayland info.cemu.Cemu` or use flatseal to block access to the wayland socket.

Doesn't seem to happen on when forcing x11, thanks!
